details:
  namespace: student14-bookinfo-uat
  image: ghcr.io/jakkapongqcue/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student14/details(/|$)(.*)"
  serviceType: ClusterIP